-- DROP DATABASE AGENCIA_VIAJES;
-- CREATE DATABASE AGENCIA_VIAJES;
USE AGENCIA_VIAJES;

-- CREATE TABLE PREFIJOS(
-- PAIS VARCHAR(50),
-- PREFIJO VARCHAR (10) PRIMARY KEY);

-- CREATE TABLE PASAJERO(
-- NOMBRE VARCHAR (100),
-- APELLIDOS VARCHAR (100),
-- SEXO ENUM('HOMBRE', 'MUJER', 'OTRO'),
-- EMAIL VARCHAR(100) PRIMARY KEY,
-- CONTRASEÑA1 VARCHAR(100), 
-- CONTRASEÑA2 VARCHAR(100),
-- TELEFONO INT,
-- PREFIJO VARCHAR (10),
-- FOREIGN KEY (PREFIJO) REFERENCES PREFIJOS (PREFIJO));

SELECT *FROM PREFIJOS;
SELECT *FROM PASAJERO;
